/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MATERIALS_GATEWAYS_SYSTEMS;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javafx.scene.input.DataFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Gatepass_print extends javax.swing.JFrame {
   
    String MD1 ;
     String GT1 ;
      String P1 ;
       String PD1 ;
        String B1 ;
      String  gatepass_no=null;
        int  RGTNO=0;
         int RPNO=0;
           String q=null;
     String get=null;
     int randomNumber=0;
     String NAME;
     String Datee;
    
           /**
     * Creates new form Gatepass_print
     */
    public Gatepass_print() {
        initComponents();
    }
    
   
        
    
    
    public Gatepass_print(String M_D ,String G_T ,String P,String P_D ,String B ,String is3)  
    {
          initComponents();
        MD1=M_D ;
        GT1=G_T ;
        P1=P ;
        PD1=P_D ;
        B1=B ;
        NAME=is3;
        
       
        
     get=GPNGF();
         randomNumber =RandomFunc();
         Datee=GenrateDate();
        gatepass_no=randomNumber+""+get;
        jTextArea1.append("\nGATEPASS NUM*   :          "+gatepass_no);
         jTextArea1.append("\n\nDate                        :         "+Datee  );
        jTextArea1.append("\n\nMATERIAL DISc*    :          "+MD1);
        jTextArea1.append("\n\nGATEPASS TYPE   :          "+GT1);
        jTextArea1.append("\n\nPURPOSE              :          "+P1);
        jTextArea1.append("\n\nPURPOSE DISC*   :          "+PD1);
        jTextArea1.append("\n\nBEARER                :           "+B1);      
        jTextArea1.append("\n\nISSUER                  :          "+NAME);      
        
    }
    
    public int RandomFunc(){
        
        
        
        Random rand=new Random();
        int number;
        
        
            number=rand.nextInt(9999);
                   return number;
        
        
        
    }
    
    public String GPNGF(){
    
        
        
        if(GT1.equalsIgnoreCase("Returnable gatepass")){
          
            RGTNO=199;
        }
        else {
        
                RGTNO=399;
        }
        
        
        
        if(P1.equalsIgnoreCase("REPAIR")){
              RPNO=452;
        }
           else if(P1.equalsIgnoreCase("return")){
              RPNO=253;
        }           else if(P1.equalsIgnoreCase("distroy")){ 
              RPNO =521;
       }
          else if(P1.equalsIgnoreCase("sold")){ 
              RPNO =784;
       }
          else{
              RPNO=147;
          }
         q=RGTNO+""+RPNO;

  return q;
    }
    
    
    public  String  GenrateDate(){
      DateFormat  df=new SimpleDateFormat("dd/mm/yyyy");
        Date date=new Date();
        Calendar calender=Calendar.getInstance();
         String s=df.format(date);
 return s;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Indian Oil Corporation Limited");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 310, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MATERIALS_GATEWAYS_SYSTEMS/iocl.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 100));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log-off");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 90, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Print");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 90, 30));

        jButton3.setBackground(new java.awt.Color(102, 255, 51));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 90, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 204, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 670, 330));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Num*  : Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DISC* : Discription ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        try {
            boolean complete=jTextArea1.print();
            if(complete){
                JOptionPane.showMessageDialog(null,"Print Succes");
            }
       else{
      JOptionPane.showMessageDialog(null, "failure");
        }
        } catch (PrinterException e) {
        JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
        
        
        
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        String gn=gatepass_no;
String dd=Datee;
String mmd=MD1;
String ggt=GT1;
String pp= P1;
String ppd=PD1;
String bb=B1;
String name=NAME;
String  query="insert  into gpd"
        +"(Gatepass_number , Date , material_disc , gatepass_type , purpose , purpose_disc , bearer ,  issuer)" 
        +"values(?,?,?,?,?,?,?,?)";
       
       try{  


Connection  con=(Connection) DriverManager.getConnection( "jdbc:mysql://localhost:3306/gpddb","root","1998");  

PreparedStatement pst=con.prepareStatement(query);

           pst.setString(1,gn);
                pst.setString(2,dd);
             pst.setString(3,mmd);
              pst.setString(4,ggt);
             pst.setString(5,pp);
               pst.setString(6,ppd);
                 pst.setString(7,bb);
                   pst.setString(8,name);
                   
                   pst.executeUpdate();
                   JOptionPane.showMessageDialog(null,"Saved.");

}
catch(Exception  e){
    JOptionPane.showMessageDialog(null,  "Server error !");

}  
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gatepass_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gatepass_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gatepass_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gatepass_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gatepass_print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
